name: Deployment Pipeline

on:
    push: # Evento de GIT q espera
        branches:
            - "master" # Mi rama principal

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run eslint
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
            - name: E2E test
              uses: cypress-io/github-action@v6  # Action from CYPRESS
              with:
                command: npm run test:e2e # Command to execute
                start: npm run dev # Runs APP
                wait-on: http://localhost:5173 # URL server